FROM node:14-alpine
RUN mkdir -p /app
WORKDIR /app
COPY . .
RUN npm install
RUN npm install next-auth
RUN npm install axios
RUN npm cache clean --force
RUN npm run build
CMD ["npm", "run" ,"dev"]
EXPOSE 3000